version: "3"
services:
  postgres:
    image: postgres:12.19-bullseye
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: task_manager,task_manager_test
    ports:
      - "5433:5432"
    expose:
      - 5432
    volumes:
      - ./dockerDatabase/init:/docker-entrypoint-initdb.d
      - ./dockerDatabase/data:/var/lib/postgresql/data
  server:
    build: ..
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/task_management
    depends_on:
      - postgres

