create table IF NOT EXISTS user_table(
                                         id int primary key generated by default as identity,
                                         username varchar not null unique,
                                         mail varchar not null unique,
                                         password varchar not null
);

create table IF NOT EXISTS task(
                     id int primary key generated by default as identity,
                     title varchar,
                     description varchar,
                     state varchar,
                     priority varchar,
                     owner_id int references user_table (id),
                     executor_id int references user_table (id)
);

create table IF NOT EXISTS comment(
                        id int primary key generated by default as identity,
                        text varchar,
                        user_id int references user_table(id),
                        task_id int references task(id)
);