DROP TABLE IF EXISTS  comment;
DROP TABLE IF EXISTS task;
DROP TABLE IF EXISTS  user_table;

ALTER SEQUENCE IF EXISTS user_table_id_seq restart;
ALTER SEQUENCE IF EXISTS task_id_seq restart;
ALTER SEQUENCE IF EXISTS comment_id_seq restart;

create table  user_table(
                           id int primary key generated by default as identity,
                           username varchar,
                           mail varchar not null unique ,
                           password varchar not null
);

create table task(
                     id int primary key generated by default as identity,
                     title varchar,
                     description varchar,
                     state varchar,
                     priority varchar,
                     owner_id int references user_table (id),
                     executor_id int references user_table (id)
);

create table comment(
                        id int primary key generated by default as identity,
                        text varchar,
                        user_id int references user_table(id),
                        task_id int references task(id)
);


insert into user_table (username, mail, password) VALUES ('base', 'base@mail.ru', 'password');
insert into user_table (username, mail, password) VALUES ('test1', 'test1@mail.ru', 'password');
insert into user_table (username, mail, password) VALUES ('test2', 'test2@mail.ru', 'password');

insert into task (title, description, owner_id) values ('task_base', 'test base task', 1);
insert into task (title, description, owner_id, executor_id) values ('task1', 'test task1', 2, 3);
insert into task (title, description, owner_id, executor_id) values ('task2', 'test task2', 3, 2);
